#!/usr/bin/env python3
"""Resolve one immutable colour plan for singers, spectrum, and progress."""

from __future__ import annotations

import hashlib
import json
import re
import unicodedata
from pathlib import Path
from typing import Any, Mapping

from scripts import karaoke_cover_palette


COLOR_PLAN_SCHEMA = "karaoke-color-plan/v1"
PALETTE_SCHEMA = "karaoke-cover-palette/v1"
HEX_COLOR = re.compile(r"#[0-9A-F]{6}")


class KaraokeColorPlanError(ValueError):
    """Raised when a colour plan cannot be resolved without guessing."""


def normalize_hex_color(value: object, *, field: str = "color") -> str:
    color = str(value or "").strip().upper()
    if not HEX_COLOR.fullmatch(color):
        raise KaraokeColorPlanError(f"invalid {field}: {value!r}")
    return color


def _canonical_hash(value: Mapping[str, Any]) -> str:
    encoded = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def load_composition_palette(composition_path: Path) -> dict[str, Any]:
    """Load and validate the cover palette embedded beside a composition."""

    metadata_path = composition_path.with_suffix(".json")
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise KaraokeColorPlanError(
            f"could not load composition metadata {metadata_path}: {error}"
        ) from error
    palette = metadata.get("cover_palette")
    if not isinstance(palette, Mapping):
        raise KaraokeColorPlanError(
            f"composition metadata has no cover_palette: {metadata_path}"
        )
    if palette.get("schema_version") != PALETTE_SCHEMA:
        raise KaraokeColorPlanError(
            f"unsupported cover palette schema: {palette.get('schema_version')!r}"
        )
    try:
        karaoke_cover_palette.validate_palette_report(
            palette,
            expected_color_count=8,
        )
    except (TypeError, ValueError) as error:
        raise KaraokeColorPlanError(f"invalid embedded cover palette: {error}") from error
    current_generator_sha256 = hashlib.sha256(
        Path(karaoke_cover_palette.__file__).resolve().read_bytes()
    ).hexdigest()
    if palette.get("generator_sha256") != current_generator_sha256:
        raise KaraokeColorPlanError(
            "composition cover palette was not generated by the current extractor"
        )
    cover = metadata.get("cover")
    if not isinstance(cover, Mapping) or cover.get("sha256") != palette.get(
        "cover_sha256"
    ):
        raise KaraokeColorPlanError(
            "composition cover identity does not match its embedded palette"
        )
    values = palette.get("colors")
    if not isinstance(values, list) or len(values) != 8:
        raise KaraokeColorPlanError("cover palette must contain exactly eight colors")
    colors = [
        normalize_hex_color(value, field=f"cover palette color {index}")
        for index, value in enumerate(values)
    ]
    if len(colors) != len(set(colors)):
        raise KaraokeColorPlanError("cover palette colors must be unique")
    if normalize_hex_color(palette.get("primary"), field="palette primary") != colors[0]:
        raise KaraokeColorPlanError("cover palette primary must equal colors[0]")
    if normalize_hex_color(palette.get("secondary"), field="palette secondary") != colors[1]:
        raise KaraokeColorPlanError("cover palette secondary must equal colors[1]")
    return {**palette, "colors": colors, "metadata_path": str(metadata_path.resolve())}


def parse_singer_color_overrides(values: list[str]) -> dict[str, str]:
    """Parse repeatable ``SINGER_ID=#RRGGBB`` render-only overrides."""

    overrides: dict[str, str] = {}
    for value in values:
        singer_id, separator, raw_color = value.partition("=")
        singer_id = singer_id.strip()
        if not separator or not singer_id:
            raise KaraokeColorPlanError(
                f"invalid singer color override {value!r}; expected SINGER_ID=#RRGGBB"
            )
        if singer_id in overrides:
            raise KaraokeColorPlanError(f"duplicate singer color override: {singer_id}")
        overrides[singer_id] = normalize_hex_color(
            raw_color,
            field=f"singer override {singer_id}",
        )
    return overrides


def _project_singers(project: object) -> tuple[list[object], dict[str, object]]:
    singers = list(getattr(project, "singers", None) or [])
    by_id: dict[str, object] = {}
    defaults = 0
    for singer in singers:
        singer_id = str(getattr(singer, "id", "") or "").strip()
        if not singer_id or singer_id in by_id:
            raise KaraokeColorPlanError(f"invalid or duplicate singer_id: {singer_id!r}")
        by_id[singer_id] = singer
        defaults += int(bool(getattr(singer, "is_default", False)))
    if defaults != 1:
        raise KaraokeColorPlanError(
            f"project must declare exactly one default singer; found={defaults}"
        )
    return singers, by_id


def _default_singer_id(singers: list[object]) -> str:
    return next(
        str(getattr(singer, "id", "") or "").strip()
        for singer in singers
        if bool(getattr(singer, "is_default", False))
    )


def _character_has_display_text(character: object) -> bool:
    text = str(getattr(character, "char", "") or "")
    return any(
        not value.isspace() and unicodedata.category(value)[0] not in {"C", "Z"}
        for value in text
    )


def singer_first_appearance_order(project: object) -> list[str]:
    """Return active singer IDs in effective character-appearance order."""

    singers, by_id = _project_singers(project)
    default_id = _default_singer_id(singers)
    ordered: list[str] = []
    for sentence in getattr(project, "sentences", None) or []:
        sentence_id = str(getattr(sentence, "singer_id", "") or "").strip()
        characters = getattr(sentence, "characters", None) or []
        for character in characters:
            if not _character_has_display_text(character):
                continue
            singer_id = (
                str(getattr(character, "singer_id", "") or "").strip()
                or sentence_id
                or default_id
            )
            if singer_id not in by_id:
                raise KaraokeColorPlanError(
                    f"unknown effective singer_id: {singer_id!r}"
                )
            if singer_id not in ordered:
                ordered.append(singer_id)
    return ordered


def resolve_color_plan(
    project: object,
    *,
    composition_path: Path,
    policy: str = "cover",
    singer_overrides: Mapping[str, str] | None = None,
    spectrum_color: str | None = None,
    progress_color: str | None = None,
) -> dict[str, Any]:
    """Resolve the single colour fact consumed by ASS and video rendering."""

    if policy not in {"cover", "project"}:
        raise KaraokeColorPlanError(f"unsupported color policy: {policy!r}")
    palette = load_composition_palette(composition_path)
    singers, by_id = _project_singers(project)
    order = singer_first_appearance_order(project)
    colors = list(palette["colors"])
    if policy == "cover" and len(colors) < len(order):
        raise KaraokeColorPlanError(
            f"cover palette has {len(colors)} colors for {len(order)} active singers"
        )
    overrides = {
        singer_id: normalize_hex_color(color, field=f"singer override {singer_id}")
        for singer_id, color in (singer_overrides or {}).items()
    }
    unknown = sorted(set(overrides) - set(by_id))
    if unknown:
        raise KaraokeColorPlanError(f"singer color overrides reference unknown IDs: {unknown}")
    spectrum_override = (
        normalize_hex_color(spectrum_color, field="spectrum color")
        if spectrum_color is not None
        else None
    )
    progress_override = (
        normalize_hex_color(progress_color, field="progress color")
        if progress_color is not None
        else None
    )
    assignments: list[dict[str, Any]] = []
    for index, singer_id in enumerate(order):
        singer = by_id[singer_id]
        project_color = normalize_hex_color(
            getattr(singer, "color", None),
            field=f"project singer color {singer_id}",
        )
        if singer_id in overrides:
            resolved = overrides[singer_id]
            source = "explicit-singer-override"
        elif index == 0 and spectrum_override is not None:
            resolved = spectrum_override
            source = "explicit-primary-slot-override"
        elif index == 1 and progress_override is not None:
            resolved = progress_override
            source = "explicit-secondary-slot-override"
        elif policy == "cover":
            resolved = colors[index]
            source = f"cover-palette[{index}]"
        else:
            resolved = project_color
            source = "singer.color"
        assignments.append(
            {
                "singer_id": singer_id,
                "singer_name": str(getattr(singer, "name", "") or ""),
                "palette_index": index,
                "role": (
                    "primary"
                    if index == 0
                    else "secondary"
                    if index == 1
                    else f"accent-{index + 1}"
                ),
                "project_color": project_color,
                "resolved_color": resolved,
                "source": source,
            }
        )
    visual_primary = (
        assignments[0]["resolved_color"]
        if assignments
        else spectrum_override or colors[0]
    )
    visual_secondary = (
        assignments[1]["resolved_color"]
        if len(assignments) > 1
        else progress_override or colors[1]
    )
    plan: dict[str, Any] = {
        "schema_version": COLOR_PLAN_SCHEMA,
        "policy": policy,
        "cover_sha256": palette.get("cover_sha256"),
        "palette_generator_sha256": palette.get("generator_sha256"),
        "palette": colors,
        "singer_order": order,
        "singers": assignments,
        "visual": {
            "spectrum_color": visual_primary,
            "progress_color": visual_secondary,
        },
        "source_sug_modified": False,
    }
    return {**plan, "color_plan_sha256": _canonical_hash(plan)}


def apply_color_plan(project: object, plan: Mapping[str, Any]) -> None:
    """Apply resolved colours to a loaded in-memory project for ASS generation."""

    _singers, by_id = _project_singers(project)
    for assignment in plan.get("singers", []):
        singer_id = str(assignment["singer_id"])
        singer = by_id[singer_id]
        color = normalize_hex_color(
            assignment["resolved_color"],
            field=f"resolved singer color {singer_id}",
        )
        change_color = getattr(singer, "change_color", None)
        if callable(change_color):
            change_color(color)
        else:
            setattr(singer, "color", color)
        setattr(singer, "_karaoke_color_source", str(assignment["source"]))
